version: '3'

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always

  item-app:
    image: livay2208/item-app:v1
    ports:
      - "80:8080"
    depends_on:
      - item-db
    restart: always

volumes:
  app-db:
